### PR TITLE
nmap 7.94 & liblinear 2.47

### PR DESCRIPTION
**Pull request by sevan**
Tested on G5 running Tiger with GCC 5.5.
nmap needs newer C++ support than apple-gcc 4.2 & 4.0 offer.
Included the liblinear update in this commit since it is a dependency that's also a C++ project however it'll happily build with GCC 4.0.
Had to resort to a bodge with sed since configure is patched locally & remotely (via github commit patches), they can hopefully be dropped with the next release of nmap.

### CODE REVIEW

**Review by mistydemeo — COMMENTED** [review]
Hmm, interestingly I can't get nmap to build. I'm seeing:

```
/usr/local/bin/gcc-7 -o ncat -Os -w -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4 -Wall  -L/usr/local/opt/lua/lib -L/usr/local/opt/libpcap/lib -L/usr/local/opt/libpcap/lib -L/usr/local/opt/flex/lib -L/usr/local/opt/bison/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl3/lib -L/usr/local/opt/perl/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -L/usr/local/opt/openssl3/lib ncat_main.o ncat_connect.o ncat_core.o ncat_posix.o ncat_listen.o ncat_proxy.o ncat_ssl.o base64.o http.o util.o sys_wrap.o http_digest.o ncat_lua.o ../nsock/src/libnsock.a ../nbase/libnbase.a -lssl -lcrypto -lpcap -lm -llua
/usr/bin/ld: Undefined symbols:
_SSL_get1_peer_certificate
_EVP_PKEY_Q_keygen
_OSSL_PROVIDER_load
```

**Comment by sevan** [comment]
Hmm, I see both `-L/usr/local/opt/openssl/lib` and `-L/usr/local/opt/openssl3/lib` It seems there's a dependency that's not been updated to `openssl3` so that's tripping things up.

**Comment by mistydemeo** [comment]
You're right - looks like it's coming from Python 3, which still uses `openssl`.

**Comment by mistydemeo** [comment]
Realized this is because I hadn't merged your python3 PR - works fine after that!

**Review by mistydemeo — APPROVED** [review]

**Pull request merged**
