### PR TITLE
Remove wine

### PR DESCRIPTION
**Pull request by ahyattdev**
Wine doesn’t run on ppc so we might as well remove it.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Installs on 10.5 Intel. (Had to bump libgphoto2 first, though.)

**Comment by ahyattdev** [comment]
Does TigerBrew have a way of making packages unavailable on specific architectures?

**Comment by tkbagz08** [comment]
Can I get it to work for me

**Comment by EricFromCanada** [comment]
> Does TigerBrew have a way of making packages unavailable on specific architectures?

See apple-gcc42 for a custom `Requirement` that allows only Tiger; this could be modified to instead check that `Hardware.cpu_type == :intel`.

**Comment by mistydemeo** [comment]
A `depends_on :arch => :intel` should be able to handle it. Sorry this slipped my mind! Would you be able to add that to the top of the dependencies?

**Comment by JL2210** [comment]
Don't forget about Winelib! It provides a MinGW-compatible compiler for building Windows apps into native executables.

**Comment by ahyattdev** [comment]
@JL2210

**Comment by ahyattdev** [comment]
Looks like it shouldn't be removed

**Pull request closed without merging**
