### PR TITLE
OpenSSL 1.1

### PR DESCRIPTION
**Pull request by mistydemeo**
This branch contains both an OpenSSL bump and a variety of packages that need to be upgraded alongside it to avoid getting broken.

### CODE REVIEW

**Comment by mistydemeo** [comment]
@sevan I've almost finished merging every PR that mentioned OpenSSL in the description. Any other of your PRs you think I should get in this batch?

**Comment by sevan** [comment]
cyrus-sasl and mutt? only mentioning it because cyrus-sasl was updated to deal from the openssl update. tor?

**Comment by mistydemeo** [comment]
OK, merged both of those!

**Comment by sevan** [comment]
Should be ok to merge, right?
I'll continue with updating the formulas.

**Review by sevan — APPROVED** [review]

**Comment by mistydemeo** [comment]
Yup, this should be fine to merge. Sorry for the delay getting back - I started a new job last week and I've been a little busy, but I want to catch up on the rest of the PRs here.

**Comment by sevan** [comment]
No worries.
Thanks, Misty.
Congrats on the new job.

**Pull request merged**
