### PR TITLE
openssl: Upgrade formula to v1.1.1u

### PR DESCRIPTION
**Pull request by sevan**
Build tested on Tiger PowerPC
With this change `brew audit openssl` has one error flagged which is `Header files that shadow system header files were installed to "tigerbrew/Cellar/openssl/1.1.1t/include"` but unsure how to address it. Pointers appreciated if this needs to be addressed before it can be merged.

### CODE REVIEW

**Comment by sevan** [comment]
Looks like it does need to be addressed.

**Comment by sevan** [comment]
Now just need need to clean up the fallout from the API change since OpenSSL 1.1.0 for anything that's not up to date. :)

**Comment by goshhhy** [comment]
i'm seeing the same behavior - TigerBrew does not work out of the box due to test failures in OpenSSL which prevent the installation of curl and git. manually installing this recipe works around the issue successfully.

**Comment by mistydemeo** [comment]
Building now. Given the number of other packages that will need to be rebuilt, I'll try to coordinate merges.

**Comment by mistydemeo** [comment]
Merged into the OpenSSL 1.1 branch.

**Pull request merged**
