### PR TITLE
Rebuild `sha256` to fix it on Tiger i386

### LINKED ISSUE #359: curl failing on 10.4.11-i386
https://gist.github.com/picklefarmer/916dc234cfa89d7abf61

### PR DESCRIPTION
**Pull request by ranma42**
The new `sha256` binary is a prebuilt copy of Aaron Gifford's sha2
available at https://www.aarongifford.com/computers/sha.html

The binary is built for PowerPC and i386 using the command line:

    cc -Wall -O2 -arch i386 -arch ppc -mmacosx-version-min=10.4 \
    -isysroot/Developer/SDKs/MacOSX10.4u.sdk \
    -DMACOSX_DEPLOYMENT_TARGET=10.4 sha2.c sha2prog.c -o sha2prog

Fixes #359 and #427.

This is an alternative to #366.

### CODE REVIEW

**Comment by ranma42** [comment]
Is there anything I should do to make this progress?

I realize that a pre-compiled binary generated from an external developer might not be acceptable for inclusion in the repository. If this is a blocker, I might be able to guide you in setting up a 10.4 VM to rebuild the binary on your machine.

Alternatively, would it be feasible for you to try and regenerate the binary so that the _read$UNIX2003 symbol is not used? I would expect it to be possible with the appropriate compiler/linker flags.

**Comment by mistydemeo** [comment]
> If this is a blocker, I might be able to guide you in setting up a 10.4 VM to rebuild the binary on your machine.

**Comment by mistydemeo** [comment]
> If this is a blocker, I might be able to guide you in setting up a 10.4 VM to rebuild the binary on your machine.

This would be really helpful! I'd prefer to build this binary myself, but I haven't been successful at getting a 10.4 VM running in Virtualbox yet.

**Comment by ranma42** [comment]
I tried to simplify the procedure as much as possible and document it [here](https://github.com/ranma42/TigerOnVBox).
Sorry if it took some time, but I wanted to try some different options.

On the bright side, I now have a much better environment than before, as it is running on the SATA controller instead of the IDE (with significantly improved performance) and I got rid of an annoying issue of two cursors being shown (one by the guest OS, one by the host OS) in slightly different positions.

Please let me know if the procedure works for you.

**Comment by mistydemeo** [comment]
Thanks so much for this - it works a charm! Got it working, and rebuilt sha2 in #465. It's working for me, can you test to see if it works for you?

**Pull request closed without merging**
