### PR TITLE
stdenv, superenv: important fixes

### PR DESCRIPTION
**Pull request by gsteemso**
superenv:  added "enable_archflags" to all three places where archflags are
    used (so they actually ARE -- at present everything on my G5 builds for
    ppc7400 no matter what you do), modifying "enable_archflags" to only add
    the K if it isn't already present; and added a pseudo-private conveni-
    ence routine "archflags_enabled?" to aid checking it within super.rb.

both:  added "un_m32" and "un_m64" routines to allow removing them when no
    longer required (important to some :universal workflows), as doing it by
    hand in a way that accounts for both stdenv and superenv is tedious,
    messy, error-prone and fragile;  under superenv this is one of the spots
    where the aforementioned convenience routine comes in handy.

### CODE REVIEW

**Comment by gsteemso** [comment]
I also altered the routines which account for what CPU is being built on to actually do so, as the only circumstance where that happens now is if you're on intel without ssse4.  The comments say it's left blank because it gets "mutated elsewhere", but neither the ENV/4.3/* build tools nor any file within the Homebrew directory tree do so that I could find.

**Comment by sevan** [comment]
So if I wanted to recreate the issues that you are addressing here what would I need to attempt? (it would be nice to confirm nothing is broken on g3, g4, i386)

**Comment by gsteemso** [comment]
I just realized that I got a small part of this backwards and need to revise it. please hold off on digging into it for a few hours until I am not wasting your time :¬(

**Comment by gsteemso** [comment]
In fact, there are two different things addressed by this PR and it really ought to have been submitted as two PRs.  I'm withdrawing it in order to do so.

**Pull request closed without merging**
