### PR TITLE
Use newer make for projects with GObject introspection

### PR DESCRIPTION
**Pull request by evanmiller**
On Tiger, building `atk` and `gdk-pixbuf` with the system-provided `make` results in errors such as:

```
  *** Need to define Atk_1_0_gir_LIBS or Atk_1_0_gir_PROGRAM.  Stop.
```

Using the brew-provided `make` fixes the issue.

### CODE REVIEW

**Comment by evanmiller** [comment]
See also #481 - probably these formulas should use a standard solution... I believe it's sufficient to change

    depends_on "gobject-introspection"

to

    depends_on "gobject-introspection" => :build

And then `system "make"` to `make`. The `gobject-introspection` formula has brew's `make` as a build-time requirement, so the formulas won't need to require `make` themselves.

**Review by ticky — APPROVED** [review]
I've just tested this while attempting to confirm the fixes in #738, and along with the changes in #745, this works.

**Comment by ticky** [comment]
Oh, one comment is that `gtk+` is [still marked as requiring Leopard](https://github.com/mistydemeo/tigerbrew/blob/d28bbe7cd204048e48639e2e37b407bb588cf5f0/Library/Formula/gtk%2B.rb#L23), I haven't yet built that on Tiger, but I presume this means you tested that?

**Comment by ticky** [comment]
Oh, and the dependency on `make` via `gobject-introspection` doesn't appear to work on my machine unless explicitly declared in these dependencies. From what I can tell we need both, unfortunately.

**Comment by ticky** [comment]
`gtk+` seems to need similar changes to #738 around `NSTextInputClient`. I've yet to find any `gtk+3` software which doesn't transitively depend on `gtk+` - is there any? In any case this isn't a showstopper, just means there's more to do :)

**Review by mistydemeo — APPROVED** [review]

**Pull request merged**
