### PR TITLE
gawk: Upgrade formula to v5.3.0

### PR DESCRIPTION
**Pull request by sevan**

### CODE REVIEW

**Comment by mistydemeo** [comment]
The build's currently failing for me in `make check`, with both GCC 4.0 and 4.2:

```
============== _dbugeval4 =============
--- dbugeval4.ok        2023-02-12 11:18:38.000000000 -0800
+++ _dbugeval4  2023-08-20 21:17:02.000000000 -0700
@@ -1,5 +1,3 @@
 gawk: cmd. line:1: fatal: function `a' not defined
 fatal error during eval, need to restart.
-Restarting ...
-1
-EXIT CODE: 2
+Failed to restart debuggerEXIT CODE: 1
make[2]: *** [check] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check] Error 2
```

What compiler/OS combo did you build on?

**Comment by sevan** [comment]
Either I ignored the checked or I tested on Leopard. Running it now on Tiger powerpc, I get 2 test failures with GCC 4.0.1. I have tried turning optimisations off.
I'll get this fixed and follow up when it is ready merge with all tests passing.

```
============== _clos1way2 =============                                                                                                          
--- clos1way2.ok        2019-08-28 19:43:58.000000000 +0100                                                                                      
+++ _clos1way2  2023-08-21 23:06:42.000000000 +0100                                                                                              
@@ -1,4 +1,4 @@                                                                                                                                  
-gawk: clos1way2.awk:5: (FILENAME=- FNR=1) warning: fflush: cannot flush: two-way pipe `cat - 1>&2 && sleep 2' has closed write end              
 test                                                                                                                                            
+gawk: clos1way2.awk:5: (FILENAME=- FNR=1) warning: fflush: cannot flush: two-way pipe `cat - 1>&2 && sleep 2' has closed write end              
 gawk: clos1way2.awk:6: (FILENAME=- FNR=1) fatal: print: attempt to write to closed write end of two-way pipe                                    
 EXIT CODE: 2                                                                                                                                    
============== _dbugeval4 =============                                                                                                          
--- dbugeval4.ok        2023-02-12 19:18:38.000000000 +0000                                                                                      
+++ _dbugeval4  2023-08-21 23:06:51.000000000 +0100                                                                                              
@@ -1,5 +1,3 @@                                                                                                                                  
 gawk: cmd. line:1: fatal: function `a' not defined                                                                                              
 fatal error during eval, need to restart.                                                                                                       
-Restarting ...                                                                                                                                  
-1                                                                                                                                               
-EXIT CODE: 2                                                                                                                                    
+Failed to restart debuggerEXIT CODE: 1                                                                                                          
make[2]: *** [check] Error 1                                                                                                                     
make[1]: *** [check-recursive] Error 1                                                                                                           
make: *** [check] Error 2
```

**Comment by sevan** [comment]
Yep. On Leopard a different test fails, but when it's about to do the run, it states not to worry if it fails.
```
======== Starting machine-specific tests ========
If any of these tests fail, don't worry too much.
double1
double2
inf-nan-torture
./inf-nan-torture.ok _inf-nan-torture differ: char 140, line 13
make[2]: [inf-nan-torture] Error 1 (ignored)
intformat
======== Done with machine-specific tests ========

============== _inf-nan-torture =============
--- inf-nan-torture.ok  2022-06-02 19:18:31.000000000 +0100
+++ _inf-nan-torture    2023-08-22 14:19:50.000000000 +0100
@@ -10,7 +10,7 @@
 10 +123 123
 11 nancy 0
 12 +nancy 0
-13 +nan +nan
+13 +nan -nan
 14 inform 0
 15 +inform 0
 16 +inf +inf
make[2]: *** [check] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check] Error 2
```

**Comment by mistydemeo** [comment]
Thank you!

**Comment by sevan** [comment]
Spoke with the maintainer about the issue and again, need to dig further to investigate. It is likely that there might be a fall out on the G5, since they had a G4 and it apparently runs on there.

**Comment by sevan** [comment]
5.3.0 is fine on Tiger (g4/g5) gcc 4.0, and Leopard (g4) gcc 4.2.

**Comment by mistydemeo** [comment]
Confirmed, it's fine on my PowerMac G5 running Tiger. Thank you for following this up!

**Review by mistydemeo — APPROVED** [review]

**Pull request merged**
