### PR TITLE
gcc6 6.5.0

### PR DESCRIPTION
**Pull request by sevan**
Build tested on Tiger with GCC 4.0.1 but only with C & unintentionally Fortran support. Took some time.
Plugin support can be enabled on Tiger, as with GCC 5.5.

```
Using built-in specs.
COLLECT_GCC=bin/gcc-6
COLLECT_LTO_WRAPPER=/Sandbox/tigerbrew/Cellar/gcc6/6.5.0/libexec/gcc/powerpc-apple-darwin8.11.0/6.5.0/lto-wrapper
Target: powerpc-apple-darwin8.11.0
Configured with: ../configure --build=powerpc-apple-darwin8.11.0 --prefix=/Sandbox/tigerbrew/Cellar/gcc6/6.5.0 --libdir=/Sandbox/tigerbrew/Cellar/gcc6/6.5.0/lib/gcc/6 --enable-languages=c,fortran --program-suffix=-6 --with-gmp=/Sandbox/tigerbrew/opt/gmp --with-mpfr=/Sandbox/tigerbrew/opt/mpfr --with-mpc=/Sandbox/tigerbrew/opt/libmpc --with-isl=/Sandbox/tigerbrew/opt/isl014 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc6 6.5.0' --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --with-dwarf2 --disable-nls --disable-multilib
Thread model: posix
gcc version 6.5.0 (Homebrew gcc6 6.5.0)
```

### CODE REVIEW

**Comment by EricFromCanada** [comment]
See also: https://github.com/mistydemeo/tigerbrew/pull/572

**Comment by mistydemeo** [comment]
I have a build with the other PR running at the moment.

**Comment by EricFromCanada** [comment]
Ah, I see that now. 🫡

**Comment by mistydemeo** [comment]
Merged as 6d193d980a56acadbcbf527805da93902a073272 - confirmed the build works with this. Thank you!

**Pull request closed without merging**
