### PR TITLE
gobject-introspection: Upgrade formula to v1.60.2

### PR DESCRIPTION
**Pull request by sevan**
v1.60.2 is the last version to support autoconf.
More recent versions require meson.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Hm, looks like this won't build without a glib upgrade. Seems it needs at least 2.58.0.

**Comment by sevan** [comment]
Ah, ok. I'm running a WIP of glib 2.59.0 here so that's why it passed. Will try and finish it off and raise a pull requests in the next few days.

**Comment by sevan** [comment]
PR #989 brings in glib 2.59.0, that should unblock this and the other PRs for merging (#847, #860)

**Review by mistydemeo — APPROVED** [review]
Built! Thanks so much again for this.

**Pull request merged**
