### PR TITLE
GCC upgrade staging branch

### PR DESCRIPTION
**Pull request by mistydemeo**
This will contain the GCC 5.5 upgrade and the dependencies for the GCCs.

### CODE REVIEW

**Comment by sevan** [comment]
I have a question, I've been trying to bring the GCC 6 formula up to date with v6.5 and hit an issue building on Tiger where it errors 
```
ios_failure.o has both STABS and DWARF debugging info  
collect2: error: ld returned 1 exit status
```
Does Tigerbrew build with compiler flag `-g` by default? (or is that coming from the GCC build infra)

**Comment by mistydemeo** [comment]
Tigerbrew's default CFLAGSS don't set `-g`; that must be coming from GCC itself. I guess the bootstrap compiler is built with that so you can better investigate issues mid-build?

I'm currently building GCC 6 from #572 - I'll see if I run into issues.

**Comment by sevan** [comment]
I'm currently attempting a build with the following set
```
ENV.append_to_cflags "-gstabs0"
ENV.append "CXXFLAGS", "-gstabs0"
```
and `languages = %w[c]` for a quick turn around. :)

**Comment by sevan** [comment]
```
diff --git a/Library/Formula/gcc6.rb b/Library/Formula/gcc6.rb
index f16f2d5650..fb67cfff56 100644
--- a/Library/Formula/gcc6.rb
+++ b/Library/Formula/gcc6.rb
@@ -21,9 +21,9 @@ class Gcc6 < Formula
 
   desc "The GNU Compiler Collection"
   homepage "https://gcc.gnu.org"
-  url "https://ftpmirror.gnu.org/gcc/gcc-6.2.0/gcc-6.2.0.tar.bz2"
-  mirror "https://ftp.gnu.org/gnu/gcc/gcc-6.2.0/gcc-6.2.0.tar.bz2"
-  sha256 "9944589fc722d3e66308c0ce5257788ebd7872982a718aa2516123940671b7c5"
+  url "https://ftpmirror.gnu.org/gcc/gcc-6.5.0/gcc-6.5.0.tar.xz"
+  mirror "https://ftp.gnu.org/gnu/gcc/gcc-6.5.0/gcc-6.5.0.tar.xz"
+  sha256 "7ef1796ce497e89479183702635b14bb7a46b53249209a5e0f999bebf4740945"
 
   bottle do
     sha256 "c30c0898b73794434af820725d3b69d4f26e58357c6d2867028527ce31273b58" => :sierra
@@ -70,6 +70,16 @@ class Gcc6 < Formula
   def install
     # GCC will suffer build errors if forced to use a particular linker.
     ENV.delete "LD"
+    # GCC Bug 25127
+    # https://gcc.gnu.org/bugzilla//show_bug.cgi?id=25127
+    # ../../../libgcc/unwind.inc: In function '_Unwind_RaiseException':
+    # ../../../libgcc/unwind.inc:136:1: internal compiler error: in rs6000_emit_prologue, at config/rs6000/rs6000.c:26535
+    ENV.no_optimization if Hardware::CPU.type == :ppc
+    # Make sure we don't generate STABS data
+    # /usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: .libs/libstdc++.lax/libc++98convenience.a/ios_failure.o has both STABS and DWARF debugging 
info
+    # collect2: error: ld returned 1 exit status
+    ENV.append_to_cflags "-gstabs0"
+    ENV.append "CXXFLAGS", "-gstabs0"
 
     # Otherwise libstdc++ will be incorrectly tagged with cpusubtype 10 (G4e)
     # https://github.com/mistydemeo/tigerbrew/issues/538
@@ -111,9 +121,6 @@ class Gcc6 < Formula
       "--enable-stage1-checking",
       "--enable-checking=release",
       "--enable-lto",
-      # Use 'bootstrap-debug' build configuration to force stripping of object
-      # files prior to comparison during bootstrap (broken by Xcode 6.3).
-      "--with-build-config=bootstrap-debug",
       # A no-op unless --HEAD is built because in head warnings will
       # raise errors. But still a good idea to include.
       "--disable-werror",
@@ -123,13 +130,17 @@ class Gcc6 < Formula
 
     # "Building GCC with plugin support requires a host that supports
     # -fPIC, -shared, -ldl and -rdynamic."
-    args << "--enable-plugin" if MacOS.version > :leopard
+    args << "--enable-plugin" if MacOS.version > :tiger
 
     # The pre-Mavericks toolchain requires the older DWARF-2 debugging data
     # format to avoid failure during the stage 3 comparison of object files.
     # See: http://gcc.gnu.org/bugzilla/show_bug.cgi?id=45248
     args << "--with-dwarf2" if MacOS.version <= :mountain_lion
 
+    # Use 'bootstrap-debug' build configuration to force stripping of object
+    # files prior to comparison during bootstrap (broken by Xcode 6.3).
+    args << "--with-build-config=bootstrap-debug" if MacOS.version >= :mavericks
+
     args << "--disable-nls" if build.without? "nls"
 
     if build.with?("java") || build.with?("all-languages")
```

**Comment by sevan** [comment]
> and `languages = %w[c]` for a quick turn around. :)

TIL that we build with Fortran support by default, so I'm on my way to building a compiler with C & Fortran support :D
Build is still going.

**Comment by sevan** [comment]
Currently attempting to build GCC 7.5.0 with the following diff (restricted to just C language support for the test)

```
diff --git a/Library/Formula/gcc.rb b/Library/Formula/gcc.rb
index 8d570ac5be..9b298364ab 100644
--- a/Library/Formula/gcc.rb
+++ b/Library/Formula/gcc.rb
@@ -21,9 +21,9 @@ class Gcc < Formula
 
   desc "GNU compiler collection"
   homepage "https://gcc.gnu.org"
-  url "https://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz"
-  mirror "https://ftpmirror.gnu.org/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz"
-  sha256 "832ca6ae04636adbb430e865a1451adf6979ab44ca1c8374f61fba65645ce15c"
+  url "https://ftp.gnu.org/gnu/gcc/gcc-7.5.0/gcc-7.5.0.tar.xz"
+  mirror "https://ftpmirror.gnu.org/gcc/gcc-7.5.0/gcc-7.5.0.tar.xz"
+  sha256 "b81946e7f01f90528a1f7352ab08cc602b9ccc05d4e44da4bd501c5a189ee661"
 
   bottle do
     sha256 "dfe5debb5b2d22c65673a38bfc1902042d7094702f49ff3cdfa2ecb30d09308e" => :tiger_g3
@@ -47,6 +47,8 @@ class Gcc < Formula
     depends_on "cctools" => :build
   end
 
+  # Bug 21514 - [DR 488] templates and anonymous enum - fixed in 4.0.2
+  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=21514
   fails_with :gcc_4_0
   fails_with :llvm
 
@@ -74,17 +76,14 @@ class Gcc < Formula
     sha256 "17afaf7daec1dd207cb8d06a7e026332637b11e83c3ad552b4cd32827f16c1d8"
   end
 
-  # This patch fixes the build on PPC
-  # https://gcc.gnu.org/ml/gcc-testresults/2017-01/msg02971.html
-  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80865
-  patch do
-    url "https://gist.githubusercontent.com/mistydemeo/d35fcc040587cc75bd24d3464e93a45d/raw/c5fe1f0c6393526ff45803b0fc14e028149a245e/gcc_altivec.
patch"
-    sha256 "09a795d013ec3e96107bfb9d5c6bba821cc867b88c3bce494ae1564bfd4ababd"
-  end
-
   def install
     # GCC will suffer build errors if forced to use a particular linker.
     ENV.delete "LD"
+    # GCC Bug 25127
+    # https://gcc.gnu.org/bugzilla//show_bug.cgi?id=25127
+    # ../../../libgcc/unwind.inc: In function '_Unwind_RaiseException':
+    # ../../../libgcc/unwind.inc:136:1: internal compiler error: in rs6000_emit_prologue, at config/rs6000/rs6000.c:26535
+    ENV.no_optimization if Hardware::CPU.type == :ppc
 
     # Otherwise libstdc++ will be incorrectly tagged with cpusubtype 10 (G4e)
     # https://github.com/mistydemeo/tigerbrew/issues/538
@@ -100,7 +99,8 @@ class Gcc < Formula
     #  - Ada, which requires a pre-existing GCC Ada compiler to bootstrap
     #  - Go, currently not supported on macOS
     #  - BRIG
-    languages = %w[c c++ objc obj-c++ fortran]
+    #languages = %w[c c++ objc obj-c++ fortran]
+    languages = %w[c]
 
     # JIT compiler is off by default, enabling it has performance cost
     languages << "jit" if build.with? "jit"
@@ -124,7 +124,7 @@ class Gcc < Formula
 
     # "Building GCC with plugin support requires a host that supports
     # -fPIC, -shared, -ldl and -rdynamic."
-    args << "--enable-plugin" if MacOS.version > :leopard
+    args << "--enable-plugin" if MacOS.version > :tiger
 
     # Otherwise make fails during comparison at stage 3
     # See: http://gcc.gnu.org/bugzilla/show_bug.cgi?id=45248
```

I noticed there's a newer build of GCC 4.2 for Tiger listed here https://mac.r-project.org/tools/index-old.html
apple-gcc42 currently builds 4.2.1-5553 but that page offers 4.2.1-5566 for Tiger. I haven't attempted it but am curious if the very last version of GCC 4.2 will work ok on Tiger (4.2.4-5666.3)

**Comment by mistydemeo** [comment]
> I haven't attempted it but am curious if the very last version of GCC 4.2 will work ok on Tiger (4.2.4-5666.3)

Good question... I don't remember if there's a reason why we're using the build we are.

**Pull request merged**
