### PR TITLE
Use prdownloads.sourceforge.net

### PR DESCRIPTION
**Pull request by sevan**
Saves multiple redirects on almost all formulas where the source file is fetched
after the initial redirect from prdownloads. Using downloads.sourceforge
sometimes results in many redirects.
    
The formulas in this commit are ones which 'brew fetch' was able to download from the new URL.

The following formulas were unable to download one or more source files
```
aide
arpon
avidemux
bigdata
binwalk
bittwist
bogofilter
chadwick
checkstyle
clamav
dasm
dfu-programmer
djview4
dmtx-utils
etl
fatsort
fetchmail
geographiclib
gnu-cobol
gnuradio
gsoap
gtk-gnutella
ispc
kettle
launch4j
libdmtx
libmikmod
mediatomb
mikmod
mktorrent
mpop
msmtp
ndpi
ngspice
ntopng
ocp
open-cobol
osslsigncode
plantuml
pngcrush
quantlib
quex
re2c
rgxg
rkhunter
sstp-client
synfig
synfigstudio
upx
```

Shout out to mitie which has a 415MB dataset download.

Unrelated but from the formulas which used Sourceforge, the following had patch checksum issues:

```
==> Verifying ledger--patch-064b0e64d211224455511cd7b82736bb26e444c3af3b64936bec1501ed14c547.diff checksum
Warning: Patch reports different SHA256: 064b0e64d211224455511cd7b82736bb26e444c3af3b64936bec1501ed14c547

==> Verifying ledger--patch-c1438cbf989995dd0b4bfa426578a8763544f28788ae76f9ff5d23f1b8b17add.diff checksum
Warning: Patch reports different SHA256: c1438cbf989995dd0b4bfa426578a8763544f28788ae76f9ff5d23f1b8b17add

==> Verifying luabind--patch-00476ab7d918cc118e83ced427bac48de81ae8c2d3445d6f77e556b5d8bded5f.diff checksum
Warning: Patch reports different SHA256: 00476ab7d918cc118e83ced427bac48de81ae8c2d3445d6f77e556b5d8bded5f

==> Verifying mldonkey--patch-1fb503d37eed92390eb891878a9e6d69b778bd2f1d40b9845d18aa3002f3d739.patch checksum
Warning: Patch reports different SHA256: 1fb503d37eed92390eb891878a9e6d69b778bd2f1d40b9845d18aa3002f3d739

==> Verifying nant--patch-1194a3b5c8e65d47e606f9d0f3b348fb6fe1998db929a7f711a9e172764b8075.diff checksum
Warning: Patch reports different SHA256: 1194a3b5c8e65d47e606f9d0f3b348fb6fe1998db929a7f711a9e172764b8075

==> Verifying opensc--patch-18bd9b6220bfc03768c6a7f5324e7f3981eff0bc8b8f7eb0f5159508b43d6863.diff checksum
Warning: Patch reports different SHA256: 18bd9b6220bfc03768c6a7f5324e7f3981eff0bc8b8f7eb0f5159508b43d6863

==> Verifying par2--patch-eda0a381f944b1bc9d3d78bf4526f77620bcb01de48abcb08878178e47c833f7.1 checksum
Warning: Patch reports different SHA256: eda0a381f944b1bc9d3d78bf4526f77620bcb01de48abcb08878178e47c833f7

==> Verifying par2--patch-c4820b11376c9932ece944752ddd388fb50fcbcd47aaadda073997142952d969.2 checksum
Warning: Patch reports different SHA256: c4820b11376c9932ece944752ddd388fb50fcbcd47aaadda073997142952d969
```

### CODE REVIEW

**Comment by sevan** [comment]
I committed a change to p7zip by mistake, will take it out in the morning & mark it ready for review.

**Comment by mistydemeo** [comment]
Thank you! I'll wait until then

**Comment by sevan** [comment]
Should be good now :)

**Comment by sevan** [comment]
Hmm `prdownloads.sourceforge.net is an alias for downloads.sourceforge.net.`

**Pull request closed without merging**
